.Dd May 11, 2017
.Dt 1WF 1
.Os

.Sh 1WF
.Nm 1wf
.Nd solve 4p1w riddles

.Sh SYNOPSIS
.Nm
.Ar len
.Ar chars
.Ar dict

.Sh DESCRIPTION
.Nm
prints possible solutions for 4 pics 1 word riddles.
It takes following arguments:
.Bl -tag -width Ds
.It Ar len
The length of the searched word.
.It Ar chars
The characters provided by 4p1w.
.It Ar dict
The dictionary file.
.El

.Sh FILES
.Bl -tag -width Ds
.It Pa dict
Dictionary file included in this repository.
.It Pa /usr/share/dict/
Probably contains useful dictionary files.
.El

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
There are often multiple solutions, the right one should be within
the first 10-20 results.
.Pp
Only ASCII input can be handled.

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
